package com.tadpole.instrument.model

import kotlin.math.*

// Generated by audio-analysis/generate_range_tables.py; do not hand edit.
// Median time-normalized shape assumes approximately uniform finger speed.
internal object MeasuredRanges {
    const val LOW_TOP = 54.49140446f
    const val LOW_MIDDLE = 98.73970196f
    const val LOW_BOTTOM = 292.18012997f
    const val MID_TOP = 203.79040063f
    const val MID_MIDDLE = 388.36890790f
    const val MID_BOTTOM = 1057.63786379f
    const val HIGH_TOP = 806.26252869f
    const val HIGH_MIDDLE = 1446.45506988f
    const val HIGH_BOTTOM = 4443.67938733f
    private val curves = arrayOf(
        Curve(floatArrayOf(54.4914045f,57.450743f,60.9570905f,65.8726476f,72.2152934f,79.1116201f,84.4826975f,91.4584482f,98.739702f,107.258529f,118.733242f,131.037218f,147.132056f,177.438594f,212.538907f,246.87923f,292.18013f)),
        Curve(floatArrayOf(203.790401f,216.276037f,231.670006f,250.983193f,273.509125f,294.963746f,320.477924f,350.613646f,388.368908f,429.848172f,476.326587f,531.674851f,607.630064f,701.814974f,817.057875f,916.590929f,1057.63786f)),
        Curve(floatArrayOf(806.262529f,856.236696f,909.874703f,972.927539f,1043.45369f,1119.37423f,1202.95927f,1308.61396f,1446.45507f,1616.82648f,1799.47485f,2030.13809f,2384.85619f,2904.73949f,3466.2548f,3967.45976f,4443.67939f)),
    )
    fun frequencyAt(range: PitchRange, position: Float) = curves[range.ordinal].at(position)
    private class Curve(frequencies: FloatArray) {
        private val y = DoubleArray(frequencies.size) { ln(frequencies[it].toDouble()) }
        private val last = y.lastIndex
        private val d = DoubleArray(last) { (y[it+1]-y[it])*last }
        private val m = DoubleArray(y.size) { i -> when(i) {
            0 -> ((3*d[0]-d[1])/2).coerceIn(0.0,3*d[0])
            last -> ((3*d[last-1]-d[last-2])/2).coerceIn(0.0,3*d[last-1])
            else -> if(d[i-1]*d[i]<=0) 0.0 else 2*d[i-1]*d[i]/(d[i-1]+d[i])
        } }
        fun at(position: Float): Float {
            val p = (if(position.isFinite()) position.coerceIn(0f,1f) else .5f)*last
            val i = p.toInt().coerceAtMost(last-1); val u = (p-i).toDouble()
            return exp((2*u*u*u-3*u*u+1)*y[i] + (u*u*u-2*u*u+u)*m[i]/last +
                (-2*u*u*u+3*u*u)*y[i+1] + (u*u*u-u*u)*m[i+1]/last).toFloat()
        }
    }
}
