#!/usr/bin/env python3
"""Export measured harmonics and spatial defaults as dependency-free Kotlin.

Small methods keep JVM/Dex methods below the 64 KB bytecode limit. Full source
measurements, including the held-out third sweep, remain outside the APK.
"""
from pathlib import Path
import json

ROOT=Path(__file__).resolve().parent.parent
MODEL=json.loads((ROOT/'audio-analysis/model/range_model.json').read_text())
AUDIO=ROOT/'app/src/main/java/com/tadpole/instrument/audio'
DOMAIN=ROOT/'app/src/main/java/com/tadpole/instrument/model'

def array(values):
    return 'floatArrayOf('+','.join(f'{v:.9g}f' if '.' in f'{v:.9g}' or 'e' in f'{v:.9g}' else f'{v:.9g}.0f' for v in values)+')'

for entry in MODEL['ranges']:
    name=entry['name'].title();anchors=entry['model']['anchors']
    lines=['package com.tadpole.instrument.audio','',
        '// Generated by audio-analysis/generate_range_tables.py; do not hand edit.',
        f'// Source {entry["file"]}, SHA256 {entry["sha256"]}.',
        '// Open mouth; only sweeps 1 and 2 fit the timbre. Sweep 3 is held out.',
        f'internal object Measured{name} {{',
        f'    const val outputGain = {MODEL["output_gain"]:.9g}f',
        f'    val frequencies = {array([a["frequency"] for a in anchors])}',
        f'    val amplitudes = arrayOf('+','.join(f'a{i}()' for i in range(len(anchors)))+')',
        f'    val phases = arrayOf('+','.join(f'p{i}()' for i in range(len(anchors)))+')']
    for i,a in enumerate(anchors):
        lines.append(f'    private fun a{i}() = {array(a["amplitudes"])}')
        lines.append(f'    private fun p{i}() = {array(a["phases"])}')
    lines.append('}')
    (AUDIO/f'Measured{name}.kt').write_text('\n'.join(lines)+'\n',encoding='utf8')

lines=['package com.tadpole.instrument.model','',
    'import kotlin.math.*','',
    '// Generated by audio-analysis/generate_range_tables.py; do not hand edit.',
    '// Median time-normalized shape assumes approximately uniform finger speed.',
    'internal object MeasuredRanges {']
for entry in MODEL['ranges']:
    prefix=entry['name'];cal=entry['calibration']
    for part,key in [('TOP','top_hz'),('MIDDLE','middle_hz'),('BOTTOM','bottom_hz')]:
        lines.append(f'    const val {prefix}_{part} = {cal[key]:.8f}f')
lines+=['    private val curves = arrayOf(']
for entry in MODEL['ranges']:lines.append('        Curve('+array(entry['calibration']['frequencies'])+'),')
lines+=['    )','    fun frequencyAt(range: PitchRange, position: Float) = curves[range.ordinal].at(position)',
    '    private class Curve(frequencies: FloatArray) {',
    '        private val y = DoubleArray(frequencies.size) { ln(frequencies[it].toDouble()) }',
    '        private val last = y.lastIndex',
    '        private val d = DoubleArray(last) { (y[it+1]-y[it])*last }',
    '        private val m = DoubleArray(y.size) { i -> when(i) {',
    '            0 -> ((3*d[0]-d[1])/2).coerceIn(0.0,3*d[0])',
    '            last -> ((3*d[last-1]-d[last-2])/2).coerceIn(0.0,3*d[last-1])',
    '            else -> if(d[i-1]*d[i]<=0) 0.0 else 2*d[i-1]*d[i]/(d[i-1]+d[i])',
    '        } }',
    '        fun at(position: Float): Float {',
    '            val p = (if(position.isFinite()) position.coerceIn(0f,1f) else .5f)*last',
    '            val i = p.toInt().coerceAtMost(last-1); val u = (p-i).toDouble()',
    '            return exp((2*u*u*u-3*u*u+1)*y[i] + (u*u*u-2*u*u+u)*m[i]/last +',
    '                (-2*u*u*u+3*u*u)*y[i+1] + (u*u*u-u*u)*m[i+1]/last).toFloat()',
    '        }','    }','}']
(DOMAIN/'MeasuredRanges.kt').write_text('\n'.join(lines)+'\n',encoding='utf8')
print('Generated',[(r['name'],len(r['model']['anchors'])) for r in MODEL['ranges']], 'gain',MODEL['output_gain'])
